### ISSUE TITLE
about table 8

### ISSUE THREAD

**Issue by jcyl** [Sherrylone/M-Mix#3]
From table 8, I find that you reproduce GRACE and its variants with M-mix. I try to reproduce the results reported in the paper but can't get ideal result. Starting from base version of GRACE, I create two views based on node feature masking and generate hard
negatives Zˆ𝑎 by mp-Mix followed an MLP module. Then I use CE loss to train the model and test the model  on the dataset DBLP. The accuracy is around 0.82 which is lower than GRACE(0.84). Did I miss something or could you provide the implementation code of this part? Thanks a lot.

**Comment by Sherrylone** [comment]
In our experiments, we mainly tune the batch size, hidden dimensions, and the number of GNN layers. You can adjust the three parameters to get higher results. These codes only include the main experiments, which are modified on the baseline MVGRL, and the code of Table 8 is implemented by the other baselines. It's hard and time-consuming to integrate the two baselines, so we don't plan to rewrite the code.

**Comment by jcyl** [comment]
这是来自QQ邮箱的自动回复邮件。已收到，谢谢。

**Comment by jcyl** [comment]
Thanks a lot.
